### ISSUE TITLE
Comprehend resulting in "Error in Workflow" in Zapier

### ISSUE THREAD

**Issue by jennmainsail** [Deviated-Systems/SpamSpy-Tracker#3]
Hello!

I've been using SpamSpy for a few months to reduce spam submissions from our Squarespace website into our Salesforce CRM, which has been super helpful. In the past three weeks I've been continuously getting an "Error in workflow" message whenever this step is hit in my Zapier workflow.

My workflow is as follows:
1. New form submission in Squarespace (Trigger)
2. Comprehend in SpamSpy > Action - Content: email > Test - Error in workflow after a few seconds
3. Automation stops and I receive an error message from Zapier

I have checked my connection to SpamSpy in Zapier, including refreshing the connection as well as disconnecting and reconnecting with the API Key to no avail. I also have tested with other form fields and all return the same error.

Thanks in advance for any insight!

Platform
 - Zapier
 - Comprehend
 - Date of First Occurrence - 8/11/23 at 01:49:04 am

**Comment by JasonCheroske** [comment]
Hello @jennmainsail,

Thank you for reaching out and for your continued use of SpamSpy. We sincerely apologize for the inconvenience you've been experiencing with your Zapier workflow.

We're currently in the process of transitioning from SpamSpy V1 (Now Deprecated) to our patched V2 alpha snapshot API on Zapier. This transition is aimed at providing enhanced functionality and resolving existing issues. However, it's worth noting that the Comprehend endpoint is not available at this time.

To ensure optimal use of SpamSpy, we suggest submitting your content through the Learn endpoint for now. This will allow us to gather valuable information as a baseline. By doing so, you can make the most of Comprehend once it is live again at no extra cost.
