### ISSUE TITLE
Discord invite link doesn't work

### ISSUE THREAD

**Issue by Lvl4Sword** [Deviated-Systems/SpamSpy-Tracker#4]
It looks like the Discord invite link in the README is broken.

The Github link at the bottom of the site also tries to go to a #123, and fails. Not sure what it's doing.

**Comment by JasonCheroske** [comment]
@Lvl4Sword Hey, thanks for reaching out. We were in the process of overhauling the discord server, mostly laying the groundwork for our new discord bot. The invite link has been updated, and the server is live again.
